### ISSUE TITLE
Watch app keeps reinstalling itself

### ISSUE THREAD

**Issue by sidharthb0** [ElChoquito/AutomaticWatchFaces#1]
I've installed this on my phone using Xcode and subsequently on my watch using the Apple Watch companion app. I've also changed the wake screen setting to 'Always'.

I noticed that the wake screen goes back to my regular watch face, so I opened up the app browser on the watch to relaunch the AutoWatchFaces app. This is when I noticed the app reinstalling itself. 

This has happened multiple times over. Do you know of this and if so is there a way to sort this out? 

Thanks.

**Comment by ElChoquito** [comment]
I've never heard about this. You should retry to instal the app on your watch directly with Xcode. Select "Watchface" on Xcode and your iPhone + Apple Watch, then "run" and wait until the watch pop up the app.

PS: Please note this is not a "real watchface". If you shut down you Apple Watch screen with your hand., it will automatically pop-up the real watch face the next time. Only timer and hand shake to shutdown the screen allows you to keep the app on screen the next time.

<img width="463" alt="capture d ecran 2019-01-06 a 18 07 57" src="https://user-images.githubusercontent.com/17691505/50780892-6500d280-12a4-11e9-9bce-7c1440208aa1.png">

**Comment by sidharthb0** [comment]
Seems to have solved it. Thanks. 

Sid
