### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by Naatan** [ElChoquito/AutomaticWatchFaces#10]
Just gives a black screen when you start the app on your iphone.

**Comment by recipriversexcluson** [comment]
It can't have loaded correctly for you. I'd try and run again. Try disconnecting first and connect again

**Comment by Naatan** [comment]
Seems I used the wrong installation steps, I applied the same as I did with the TermiWatch face (using xcode).

I just uninstalled and then used the Impactor approach explained on your repo, it completes but the app does not appear on my phone. Tried it a few times. Any way to debug?

**Comment by Naatan** [comment]
Oh, getting an "Impactor Quit Unexpectedly" error during the process I just noticed (it was hidden behind a window). No further info :\

**Comment by Naatan** [comment]
Solved it with https://stackoverflow.com/a/47084160
