### ISSUE TITLE
Stability 

### ISSUE THREAD

**Issue by aresferrigni** [ElChoquito/AutomaticWatchFaces#4]
Your work is astonishing, this is basically what I have always been looking for!

As for now it’s still pretty unstable and crashes often: is it a fixable issue, regardless of the time it takes, or there is no way yet to guarantee a higher stability?

Congrats again

**Comment by ElChoquito** [comment]
Hey ! 
First of all thanks for your support. Could you give me some examples or crash please ? Which Apple Watch model do you have ?

Sylvain,

**Comment by aresferrigni** [comment]
Series 4.
It always crashes with the gesture of covering the display with the hand,
Then it will likely crash after closing a notification, but not always
Also it crashes just randomly and unpredictably but basically it won’t last more than 10-15 minutes (ofc I turned on the “always” option when having an app open)

**Comment by ElChoquito** [comment]
Hey, The app didn't crash when you cover the display with your hand. It's always return to the official AW screen it's normal, just don't turn off your screen this way. A lot of users have an AW Series 4 and no one is complaining about crashes, it's strange... for the notification freeze, it should be fix with the 1.0 !

Regards

**Comment by aresferrigni** [comment]
Perfect, thanks!
