### ISSUE TITLE
Cannot install the app on iphone

### ISSUE THREAD

**Issue by somu-1007** [ElChoquito/AutomaticWatchFaces#5]
Trying to install through Diawi, itunes and also cydia impactor

Type: iPhone X GSM/LTE (iPhone10,6) 
iOS: 12.1.4 
Screen: 375x812 @3x (1125x2436) 
Architecture: arm64 

Provisioning devices
This app's provisioning profile doesn't seem to contain your device's UDID. Contact your developers with your UDID from the device page so they can add it to the provisoning.

**Comment by somu-1007** [comment]
Udid: f2cbb736f63c1b8a952b85f6813c2cf67b6ff475

**Comment by ElChoquito** [comment]
Hey, I provide the Ipa file because people asked for it. Personally, I don't use Cydia impactor and I can't add your UDID.
