### ISSUE TITLE
Unable to install to watch when using the Reprovision method

### ISSUE THREAD

**Issue by felixfletcher** [ElChoquito/AutomaticWatchFaces#6]
Reprovision installs the app onto my phone as normal but then the Apple Watch app sits on the install process forever and doesn't make any progress.

**Comment by ElChoquito** [comment]
Hey ! Well I don't know what's could be wrong, personally I don't use this method. Maybe you will find the answer into our facebook group... Regards !

**Comment by felixfletcher** [comment]
I've just tried with the Xcode method and its worked fine. Does the Xcode signing give me an infinite signature or is it still just 7 days ?

**Comment by ElChoquito** [comment]
If you have free developer account it's 7 days !
