### ISSUE TITLE
App won‘t install on the watch

### ISSUE THREAD

**Issue by bastih1993** [ElChoquito/AutomaticWatchFaces#8]
Hi! I successfully installed and signed the App on my iPhone (unc0ver on 12.1.1 b3) using ReProvision. My problem is that if you want to install it on the Watch using the „Watch“ App it won‘t work. The install indicator is complete but stops this way or just go back to show „install“. Any recommendations? Thank you very much!

**Comment by tfarmer00** [comment]
Same here.

**Comment by ribhupanwar** [comment]
Same error for me non-jailbroken device

**Comment by hso0ooni** [comment]
Same here

**Comment by bastih1993** [comment]
Worked out for me using Xcode, successfully installed the App on my phone and was able to get it on the Watch via „Watch“ App!  I was able to use a friends Mac, don‘t own one myself. Would be great if the ReProvison Method work out fine, thank‘s for the great work anyway!

**Comment by desepticon** [comment]
Same. App installs and runs fine on my iPhone. When I go to install it through the app, the progress indicator goes around but then never appears on my phone and the "Install" text reappears.

**Comment by ElChoquito** [comment]
I personally don't use Cydia Impactor. I released the IPA file because people asked for it... If you have a Mac just use Xcode, otherwise, try ReProvision or ask for help in our facebook group...

Regards
